import { GradientTypo } from '@/components/gradient-text/GradientTipo';
import { Josefin_Sans } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import { NAV_ITEMS } from './const';
import './globals.css';

const josefin = Josefin_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '400', '700'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${josefin.variable}`}>
      <body className="container mx-auto my-[0px] flex flex-col max-w-[1228px]">
        <div className="flex items-center w-full justify-between">
          <div className="flex h-[34px] items-center margin">
            <Image
              className="dark:invert"
              src="/logo.svg"
              alt="Next.js logo"
              width={34}
              height={34}
              priority
            />
            <span>marblemountainsculpture</span>
          </div>
          <div className="flex flex-row items-center">
            {NAV_ITEMS.map((item) => {
              return (
                <Link href={item.path} className="px-2">
                  <GradientTypo text={item.title} />
                </Link>
              );
            })}
            <div className="w-1/2 h-1 mt-2 bg-gradient-to-tr from-[#000] via-[#4a1d16] to-[#833731] rounded-full" />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
